name: Add new item
description: Suggest a device to be added to the database
labels: ["new-item"]
body:
  - type: input
    id: manufacturer
    attributes:
      label: Manufacturer
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Model
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Digital Cameras
        - Film Cameras
        - LED
        - HMI
        - Tungsten
        - Other (please specify below)
    validations:
      required: true
  - type: textarea
    id: specs
    attributes:
      label: Technical specs
      description: Anything you know (sensor, mount, weight, power, etc.)
  - type: input
    id: source
    attributes:
      label: Link to datasheet / manufacturer page
    validations:
      required: true
