#!/usr/bin/env python3
"""
Imports the category tree and per-category field schemas from a Supabase-style
CSV export (categories table + category_field_schemas table) and writes:

  data/categories.json                 - full category tree (id, name, parent_id, sort_order)
  data/schemas/fields/<category_id>.json - dynamic field definitions for categories
                                            that have custom fields

Re-run this any time the source database's categories/field schemas change -
it fully regenerates both outputs from the CSVs (does not touch data/<root>/*.yaml
entries).

Usage:
  python3 scripts/import_categories.py \
      --categories-csv path/to/categories_rows.csv \
      --field-schemas-csv path/to/category_field_schemas_rows.csv
"""

import argparse
import csv
import json
import re
import shutil
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
FIELDS_DIR = DATA_DIR / "schemas" / "fields"
ADMIN_CONFIG_PATH = ROOT / "admin" / "config.yml"

DECAP_HEADER = """# Decap CMS configuration
# Docs: https://decapcms.org/docs/configuration-options/
#
# Auto-generated by scripts/import_categories.py from data/categories.json and
# data/schemas/fields/*.json - do not hand-edit the `collections:` section,
# re-run the import script instead (it takes the same source CSVs each time).

backend:
  name: github
  repo: joshuawinkler/filmequip-db
  branch: main
  base_url: https://decap-proxy.joshuawinkler.workers.dev
  auth_endpoint: auth

# Opens a PR for every change instead of writing directly to main.
# This preserves the CI validation + review requirement.
publish_mode: editorial_workflow

media_folder: "" # no image upload — images are only linked via image_url (see CONTRIBUTING.md)

collections:
"""

# category_field_schemas.field_type -> JSON Schema handling
VALID_FIELD_TYPES = {
    "text",
    "number",
    "boolean",
    "select",
    "multiselect",
    "multiselect_amounts",
}


def slugify(name: str) -> str:
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def load_categories(csv_path: Path) -> list[dict]:
    nodes = []
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            nodes.append(
                {
                    "id": row["id"],
                    "name": row["name"],
                    "parent_id": row["parent_id"] or None,
                    "sort_order": int(row["sort_order"]) if row["sort_order"] else 0,
                }
            )
    return nodes


def load_field_schemas(csv_path: Path) -> dict[str, list[dict]]:
    by_category: dict[str, list[dict]] = {}
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            field_type = row["field_type"]
            if field_type not in VALID_FIELD_TYPES:
                raise ValueError(f"Unknown field_type '{field_type}' for field '{row['field_key']}'")
            field = {
                "key": row["field_key"],
                "label": row["field_label"],
                "type": field_type,
                "sort_order": int(row["sort_order"]) if row["sort_order"] else 0,
                "filterable": row["is_filterable"].strip().lower() == "true",
                "variant": row["is_variant"].strip().lower() == "true",
            }
            if row.get("variant_color"):
                field["variant_color"] = row["variant_color"]
            if row.get("options"):
                field["options"] = json.loads(row["options"])
            by_category.setdefault(row["category_id"], []).append(field)

    for fields in by_category.values():
        fields.sort(key=lambda f: f["sort_order"])
    return by_category


def leaf_paths_under(root_id: str, children_by_parent: dict, by_id: dict) -> list[str]:
    """All root->leaf breadcrumb paths (as ' > '-joined strings) under root_id, root included."""
    paths = []

    def walk(node_id: str, path: list[str]) -> None:
        kids = sorted(children_by_parent.get(node_id, []), key=lambda n: n["sort_order"])
        if not kids:
            paths.append(" > ".join(path))
            return
        for k in kids:
            walk(k["id"], path + [k["name"]])

    walk(root_id, [by_id[root_id]["name"]])
    return paths


def ancestors_of(category_id: str, by_id: dict) -> list[str]:
    chain = []
    current = category_id
    while current:
        chain.append(current)
        current = by_id[current]["parent_id"]
    return chain


def field_to_decap_widget(field: dict) -> dict:
    base = {"label": field["label"], "name": field["key"], "required": False}
    t = field["type"]
    if t == "text":
        return {**base, "widget": "string"}
    if t == "number":
        return {**base, "widget": "number", "value_type": "float"}
    if t == "boolean":
        return {**base, "widget": "boolean", "default": False}
    if t == "select":
        return {**base, "widget": "select", "options": field["options"]}
    if t == "multiselect":
        return {**base, "widget": "select", "multiple": True, "options": field["options"]}
    if t == "multiselect_amounts":
        return {
            **base,
            "widget": "list",
            "fields": [
                {"label": "Name", "name": "name", "widget": "select", "options": field["options"]},
                {"label": "Amount", "name": "amount", "widget": "number", "value_type": "int"},
            ],
        }
    raise ValueError(f"Unknown field type: {t}")


def write_admin_config(nodes: list[dict], field_schemas: dict[str, list[dict]], by_id: dict) -> None:
    children_by_parent: dict = {}
    for n in nodes:
        children_by_parent.setdefault(n["parent_id"], []).append(n)

    collections = []
    for root in sorted((n for n in nodes if n["parent_id"] is None), key=lambda n: n["sort_order"]):
        leaf_paths = leaf_paths_under(root["id"], children_by_parent, by_id)

        # Union of fields defined anywhere in this root's subtree (Decap CMS has no
        # conditional/per-category fields, so every entry form shows all of them,
        # optionally, and contributors fill in what's relevant to their category).
        extra_fields: dict[str, dict] = {}
        for category_id, fields in field_schemas.items():
            if root["id"] in ancestors_of(category_id, by_id):
                for f in fields:
                    extra_fields.setdefault(f["key"], f)

        fields = [
            {"label": "ID", "name": "id", "widget": "string",
             "hint": "Format: manufacturer-model-slug, e.g. arri-alexa-mini-lf"},
            {"label": "Category", "name": "category", "widget": "select", "options": leaf_paths},
            {"label": "Manufacturer", "name": "manufacturer", "widget": "string"},
            {"label": "Model", "name": "model", "widget": "string"},
        ]
        for f in sorted(extra_fields.values(), key=lambda f: f["sort_order"]):
            fields.append(field_to_decap_widget(f))
        fields += [
            {"label": "Notes", "name": "notes", "widget": "text", "required": False},
            {"label": "Image URL", "name": "image_url", "widget": "string", "required": False,
             "hint": "Only freely licensed sources, e.g. Wikimedia Commons"},
            {"label": "Source / datasheet", "name": "source_url", "widget": "string", "required": False},
        ]

        slug = slugify(root["name"])
        collections.append({
            "name": slug,
            "label": root["name"],
            "folder": f"data/{slug}",
            "create": True,
            "slug": "{{id}}",
            "identifier_field": "id",
            "extension": "yaml",
            "format": "yaml",
            "summary": "{{manufacturer}} {{model}}",
            "fields": fields,
        })

    body = yaml.dump(collections, sort_keys=False, allow_unicode=True, width=100)
    with open(ADMIN_CONFIG_PATH, "w", encoding="utf-8") as f:
        f.write(DECAP_HEADER)
        f.write(body)
    print(f"→ admin/config.yml: {len(collections)} collections regenerated")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--categories-csv", required=True, type=Path)
    parser.add_argument("--field-schemas-csv", required=True, type=Path)
    args = parser.parse_args()

    nodes = load_categories(args.categories_csv)
    by_id = {n["id"]: n for n in nodes}

    # Sanity check: every parent_id must resolve to a known node.
    for n in nodes:
        if n["parent_id"] and n["parent_id"] not in by_id:
            raise ValueError(f"Category '{n['name']}' ({n['id']}) has unknown parent_id {n['parent_id']}")

    nodes.sort(key=lambda n: (n["parent_id"] or "", n["sort_order"], n["name"]))

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(DATA_DIR / "categories.json", "w", encoding="utf-8") as f:
        json.dump(nodes, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"→ data/categories.json: {len(nodes)} categories")

    field_schemas = load_field_schemas(args.field_schemas_csv)
    unknown = set(field_schemas) - set(by_id)
    if unknown:
        raise ValueError(f"Field schemas reference unknown category ids: {unknown}")

    if FIELDS_DIR.exists():
        shutil.rmtree(FIELDS_DIR)
    FIELDS_DIR.mkdir(parents=True, exist_ok=True)
    for category_id, fields in field_schemas.items():
        node = by_id[category_id]
        out = {
            "category_id": category_id,
            "category_name": node["name"],
            "fields": fields,
        }
        with open(FIELDS_DIR / f"{category_id}.json", "w", encoding="utf-8") as f:
            json.dump(out, f, ensure_ascii=False, indent=2)
            f.write("\n")
    print(f"→ data/schemas/fields/: {len(field_schemas)} category field-schema files")

    write_admin_config(nodes, field_schemas, by_id)

    # Ensure a data folder exists for every root category (top-level, parent_id is null).
    for n in nodes:
        if n["parent_id"] is None:
            folder = DATA_DIR / slugify(n["name"])
            folder.mkdir(parents=True, exist_ok=True)
            gitkeep = folder / ".gitkeep"
            if not any(folder.iterdir()):
                gitkeep.touch()
    print("✅ Import complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
