#!/usr/bin/env python3
"""
Imports the category tree and per-category field schemas from a Supabase-style
CSV export (categories table + category_field_schemas table) and writes:

  data/categories.json                 - full category tree (id, name, parent_id, sort_order)
  data/schemas/fields/<category_id>.json - dynamic field definitions for categories
                                            that have custom fields

Re-run this any time the source database's categories/field schemas change -
it fully regenerates both outputs from the CSVs (does not touch data/<root>/*.yaml
entries).

Usage:
  python3 scripts/import_categories.py \
      --categories-csv path/to/categories_rows.csv \
      --field-schemas-csv path/to/category_field_schemas_rows.csv
"""

import argparse
import csv
import json
import re
import shutil
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
FIELDS_DIR = DATA_DIR / "schemas" / "fields"
ADMIN_DIR = ROOT / "admin"

# Fork/redeploy elsewhere: change these two and re-run the import script.
GITHUB_REPO = "joshuawinkler/filmequip-db"
OAUTH_PROXY_BASE_URL = "https://decap-proxy.joshuawinkler.workers.dev"

DECAP_HEADER = f"""# Decap CMS configuration
# Docs: https://decapcms.org/docs/configuration-options/
#
# Auto-generated by scripts/import_categories.py from data/categories.json and
# data/schemas/fields/*.json - do not hand-edit the `collections:` section,
# re-run the import script instead (it takes the same source CSVs each time).

backend:
  name: github
  repo: {GITHUB_REPO}
  branch: main
  base_url: {OAUTH_PROXY_BASE_URL}
  auth_endpoint: auth

# Opens a PR for every change instead of writing directly to main.
# This preserves the CI validation + review requirement.
publish_mode: editorial_workflow

media_folder: "" # no image upload — images are only linked via image_url (see CONTRIBUTING.md)

collections:
"""

ADMIN_SITE_HTML = """<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="robots" content="noindex" />
  <title>Filmequip DB – Admin – {title}</title>
</head>
<body>
  <!-- Decap CMS loads itself and reads config.yml from the same folder -->
  <script src="https://unpkg.com/decap-cms@^3.0.0/dist/decap-cms.js"></script>
</body>
</html>
"""

ADMIN_INDEX_HTML = """<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="robots" content="noindex" />
  <title>Filmequip DB – Admin</title>
</head>
<body>
  <h1>Filmequip DB – Admin</h1>
  <p>Each top-level category has its own Decap CMS instance:</p>
  <ul>
{links}
  </ul>
</body>
</html>
"""

# category_field_schemas.field_type -> JSON Schema handling
VALID_FIELD_TYPES = {
    "text",
    "number",
    "boolean",
    "select",
    "multiselect",
    "multiselect_amounts",
}


def slugify(name: str) -> str:
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def load_categories(csv_path: Path) -> list[dict]:
    nodes = []
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            nodes.append(
                {
                    "id": row["id"],
                    "name": row["name"],
                    "parent_id": row["parent_id"] or None,
                    "sort_order": int(row["sort_order"]) if row["sort_order"] else 0,
                }
            )
    return nodes


def load_field_schemas(csv_path: Path) -> dict[str, list[dict]]:
    by_category: dict[str, list[dict]] = {}
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            field_type = row["field_type"]
            if field_type not in VALID_FIELD_TYPES:
                raise ValueError(f"Unknown field_type '{field_type}' for field '{row['field_key']}'")
            field = {
                "key": row["field_key"],
                "label": row["field_label"],
                "type": field_type,
                "sort_order": int(row["sort_order"]) if row["sort_order"] else 0,
                "filterable": row["is_filterable"].strip().lower() == "true",
                "variant": row["is_variant"].strip().lower() == "true",
            }
            if row.get("variant_color"):
                field["variant_color"] = row["variant_color"]
            if row.get("options"):
                field["options"] = json.loads(row["options"])
            by_category.setdefault(row["category_id"], []).append(field)

    for fields in by_category.values():
        fields.sort(key=lambda f: f["sort_order"])
    return by_category


def assign_slugs(nodes: list[dict]) -> dict[str, str]:
    """Slug per node, unique among siblings (same parent_id) - not globally unique,
    since folder nesting already disambiguates same-named categories under different parents."""
    by_parent: dict = {}
    for n in nodes:
        by_parent.setdefault(n["parent_id"], []).append(n)

    slug_by_id: dict[str, str] = {}
    for siblings in by_parent.values():
        used: dict[str, int] = {}
        for n in sorted(siblings, key=lambda n: n["sort_order"]):
            base = slugify(n["name"])
            count = used.get(base, 0) + 1
            used[base] = count
            slug_by_id[n["id"]] = base if count == 1 else f"{base}-{count}"
    return slug_by_id


def folder_path_of(category_id: str, by_id: dict, slug_by_id: dict) -> Path:
    chain = []
    current = category_id
    while current:
        chain.append(slug_by_id[current])
        current = by_id[current]["parent_id"]
    return Path(*reversed(chain))


def ancestors_of(category_id: str, by_id: dict) -> list[str]:
    chain = []
    current = category_id
    while current:
        chain.append(current)
        current = by_id[current]["parent_id"]
    return chain


def field_to_decap_widget(field: dict) -> dict:
    base = {"label": field["label"], "name": field["key"], "required": False}
    t = field["type"]
    if t == "text":
        return {**base, "widget": "string"}
    if t == "number":
        return {**base, "widget": "number", "value_type": "float"}
    if t == "boolean":
        return {**base, "widget": "boolean", "default": False}
    if t == "select":
        return {**base, "widget": "select", "options": field["options"]}
    if t == "multiselect":
        return {**base, "widget": "select", "multiple": True, "options": field["options"]}
    if t == "multiselect_amounts":
        return {
            **base,
            "widget": "list",
            "fields": [
                {"label": "Name", "name": "name", "widget": "select", "options": field["options"]},
                {"label": "Amount", "name": "amount", "widget": "number", "value_type": "int"},
            ],
        }
    raise ValueError(f"Unknown field type: {t}")


def collection_for_node(
    node_id: str, field_schemas: dict[str, list[dict]], by_id: dict, slug_by_id: dict
) -> dict:
    chain = list(reversed(ancestors_of(node_id, by_id)))  # root -> node (inclusive)

    own_fields: dict[str, dict] = {}
    for ancestor_id in chain:
        for f in field_schemas.get(ancestor_id, []):
            own_fields.setdefault(f["key"], f)

    fields = [
        {"label": "ID", "name": "id", "widget": "string",
         "hint": "Format: manufacturer-model-slug, e.g. arri-alexa-mini-lf"},
        {"label": "Manufacturer", "name": "manufacturer", "widget": "string"},
        {"label": "Model", "name": "model", "widget": "string"},
    ]
    for f in sorted(own_fields.values(), key=lambda f: f["sort_order"]):
        fields.append(field_to_decap_widget(f))
    fields += [
        {"label": "Notes", "name": "notes", "widget": "text", "required": False},
        {"label": "Image URL", "name": "image_url", "widget": "string", "required": False,
         "hint": "Only freely licensed sources, e.g. Wikimedia Commons"},
        {"label": "Source / datasheet", "name": "source_url", "widget": "string", "required": False},
    ]

    name = "-".join(slug_by_id[cid] for cid in chain)
    label_parts = [by_id[cid]["name"] for cid in chain]
    label_parts[0] = label_parts[0].upper()
    label = " › ".join(label_parts)
    folder = folder_path_of(node_id, by_id, slug_by_id)
    return {
        "name": name,
        "label": label,
        "folder": f"data/{folder.as_posix()}",
        "create": True,
        "slug": "{{id}}",
        "identifier_field": "id",
        "extension": "yaml",
        "format": "yaml",
        "summary": "{{manufacturer}} {{model}}",
        "fields": fields,
    }


def write_admin_sites(
    nodes: list[dict], field_schemas: dict[str, list[dict]], by_id: dict, slug_by_id: dict
) -> None:
    # Decap CMS's "nested collections" feature requires a single field schema
    # shared by every entry in the collection, and (with the default
    # subfolders behavior) an index file at every folder level - neither fits
    # a taxonomy where each category, at any depth, has its own exact
    # inherited+own field schema. Instead: one separate Decap site per
    # top-level root category (admin/<root>/), each with one plain folder
    # collection per category node in that root's subtree - leaves AND
    # parents alike, so entries can be filed directly under a parent category
    # too, not just its leaves. Folder collections are non-recursive by
    # default, so a parent's collection and its children's collections never
    # see each other's files even though they're nested on disk.
    roots = sorted((n for n in nodes if n["parent_id"] is None), key=lambda n: n["sort_order"])

    total_collections = 0
    for root in roots:
        members = [n for n in nodes if root["id"] in ancestors_of(n["id"], by_id)]
        members.sort(key=lambda n: [by_id[a]["sort_order"] for a in reversed(ancestors_of(n["id"], by_id))])
        collections = [collection_for_node(n["id"], field_schemas, by_id, slug_by_id) for n in members]

        site_dir = ADMIN_DIR / slug_by_id[root["id"]]
        site_dir.mkdir(parents=True, exist_ok=True)
        body = yaml.dump(collections, sort_keys=False, allow_unicode=True, width=100)
        with open(site_dir / "config.yml", "w", encoding="utf-8") as f:
            f.write(DECAP_HEADER)
            f.write(body)
        with open(site_dir / "index.html", "w", encoding="utf-8") as f:
            f.write(ADMIN_SITE_HTML.format(title=root["name"]))

        total_collections += len(collections)
        print(f"→ admin/{slug_by_id[root['id']]}/config.yml: {len(collections)} collections regenerated")

    links = "\n".join(
        f'    <li><a href="{slug_by_id[r["id"]]}/">{r["name"]}</a></li>' for r in roots
    )
    with open(ADMIN_DIR / "index.html", "w", encoding="utf-8") as f:
        f.write(ADMIN_INDEX_HTML.format(links=links))

    print(f"→ admin/index.html: landing page linking {len(roots)} sites")
    print(f"✅ {total_collections} total collections across {len(roots)} sites")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--categories-csv", required=True, type=Path)
    parser.add_argument("--field-schemas-csv", required=True, type=Path)
    args = parser.parse_args()

    nodes = load_categories(args.categories_csv)
    by_id = {n["id"]: n for n in nodes}

    # Sanity check: every parent_id must resolve to a known node.
    for n in nodes:
        if n["parent_id"] and n["parent_id"] not in by_id:
            raise ValueError(f"Category '{n['name']}' ({n['id']}) has unknown parent_id {n['parent_id']}")

    nodes.sort(key=lambda n: (n["parent_id"] or "", n["sort_order"], n["name"]))

    slug_by_id = assign_slugs(nodes)
    for n in nodes:
        n["slug"] = slug_by_id[n["id"]]

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(DATA_DIR / "categories.json", "w", encoding="utf-8") as f:
        json.dump(nodes, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"→ data/categories.json: {len(nodes)} categories")

    field_schemas = load_field_schemas(args.field_schemas_csv)
    unknown = set(field_schemas) - set(by_id)
    if unknown:
        raise ValueError(f"Field schemas reference unknown category ids: {unknown}")

    if FIELDS_DIR.exists():
        shutil.rmtree(FIELDS_DIR)
    FIELDS_DIR.mkdir(parents=True, exist_ok=True)
    for category_id, fields in field_schemas.items():
        node = by_id[category_id]
        out = {
            "category_id": category_id,
            "category_name": node["name"],
            "fields": fields,
        }
        with open(FIELDS_DIR / f"{category_id}.json", "w", encoding="utf-8") as f:
            json.dump(out, f, ensure_ascii=False, indent=2)
            f.write("\n")
    print(f"→ data/schemas/fields/: {len(field_schemas)} category field-schema files")

    write_admin_sites(nodes, field_schemas, by_id, slug_by_id)

    # Create the full nested folder tree (root -> every descendant), mirroring
    # data/categories.json exactly, so entries can live at any category depth.
    # Only leaf folders (no children) get a .gitkeep - git doesn't track empty
    # directories, and intermediate folders are already implied by their
    # descendants' files.
    has_children = {n["parent_id"] for n in nodes if n["parent_id"]}
    for n in nodes:
        folder = DATA_DIR / folder_path_of(n["id"], by_id, slug_by_id)
        folder.mkdir(parents=True, exist_ok=True)
        if n["id"] not in has_children:
            (folder / ".gitkeep").touch()
    print(f"→ data/<root>/...: nested folder tree created for {len(nodes)} categories")
    print("✅ Import complete.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
